export const GET_RESOURCE = 'GET_RESOURCE'
export const GET_APPOINTMENT = 'GET_APPOINTMENT'
export const GET_APPOINTMENT_BY_WEEK = 'GET_APPOINTMENT_BY_WEEK'
export const SELECT_RESOURCE = 'SELECT_RESOURCE'
