export const GET_RESOURCE = 'GET_RESOURCE'
export const GET_APPOINTMENT = 'GET_APPOINTMENT'
export const GET_CLASS = 'GET_CLASS'
export const GET_BOOK = 'GET_BOOK'
export const GET_APPOINTMENT_BY_WEEK = 'GET_APPOINTMENT_BY_WEEK'
export const SELECT_RESOURCE = 'SELECT_RESOURCE'

export const SET_STARTDATE = 'SET_STARTDATE'
export const SET_VIEWMODE = 'SET_VIEWMODE'
